schemaforge:

  standards:

    audit:

      enabled: true

      columns:

        - name: CREATED_BY
          dataType: VARCHAR2(50)
          nullable: false
          comment: "Creation user"


        - name: CREATED_DATE
          dataType: TIMESTAMP
          nullable: false
          comment: "Creation timestamp"


        - name: LAST_MODIFIED_BY
          dataType: VARCHAR2(50)
          nullable: false
          comment: "Last modification user"


        - name: LAST_MODIFIED_DATE
          dataType: TIMESTAMP
          nullable: false
          comment: "Last modification timestamp"