package com.behsazan.schemaforge.generation.ddl.generator.table.oracle;

import com.behsazan.schemaforge.dialect.DatabaseCapability;
import com.behsazan.schemaforge.dialect.DatabaseDialect;
import com.behsazan.schemaforge.domain.model.Column;
import com.behsazan.schemaforge.generation.ddl.generator.table.ColumnDefinitionGenerator;
import com.behsazan.schemaforge.generation.ddl.generator.table.DataTypeSqlRenderer;
import com.behsazan.schemaforge.generation.ddl.generator.table.IdentifierSqlRenderer;
import com.behsazan.schemaforge.generation.ddl.generator.table.TableGenerationException;
import java.util.Objects;

public final class OracleColumnDefinitionGenerator implements ColumnDefinitionGenerator {
    private final IdentifierSqlRenderer identifierRenderer = new IdentifierSqlRenderer();
    private final DataTypeSqlRenderer dataTypeRenderer = new DataTypeSqlRenderer();

    @Override
    public String generate(Column column, DatabaseDialect dialect) {
        Objects.requireNonNull(column, "column must not be null");
        Objects.requireNonNull(dialect, "dialect must not be null");
        StringBuilder sql = new StringBuilder();
        sql.append(identifierRenderer.render(column.name(), dialect))
                .append(' ')
                .append(dataTypeRenderer.render(column.dataType(), dialect));
        if (column.identity()) {
            if (!dialect.supports(DatabaseCapability.IDENTITY)) {
                throw new TableGenerationException("Identity columns are not supported by " + dialect.name());
            }
            sql.append(" GENERATED BY DEFAULT AS IDENTITY");
        }
        if (column.defaultValue().isPresent()) {
            sql.append(" DEFAULT ").append(column.defaultValue().expression());
        }
        if (!column.nullable()) {
            sql.append(" NOT NULL");
        }
        return sql.toString();
    }
}
