package com.behsazan.schemaforge.generation.postgresql;

import com.behsazan.schemaforge.dialect.postgresql.PostgreSqlDialect;
import com.behsazan.schemaforge.domain.enums.IndexType;
import com.behsazan.schemaforge.domain.enums.SortDirection;
import com.behsazan.schemaforge.domain.model.*;
import com.behsazan.schemaforge.domain.valueobject.*;
import com.behsazan.schemaforge.generation.ddl.generator.script.TableScriptGenerator;
import com.behsazan.schemaforge.generation.ddl.generator.table.TableDdlGenerator;
import com.behsazan.schemaforge.generation.ddl.generator.table.postgresql.PostgreSqlColumnDefinitionGenerator;
import com.behsazan.schemaforge.generation.ddl.model.RenderContext;
import com.behsazan.schemaforge.generation.ddl.model.ScriptOptions;
import com.behsazan.schemaforge.generation.ddl.renderer.postgresql.PostgreSqlDdlRenderer;
import java.time.Clock;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PostgreSqlTableScriptGeneratorTest {
    @Test void generatesCompletePostgreSqlTableScriptFromCanonicalOracleTypeNames() {
        Table table = Table.builder("SALES", "ORDER")
                .description("Customer order")
                .addColumn(new Column(Identifier.of("ID"), DataType.numeric("NUMBER", 19, 0), false,
                        null, new Description("Identifier"), true, 1))
                .addColumn(Column.required("CUSTOMER_NAME", DataType.varchar("VARCHAR2", 200)))
                .addColumn(Column.nullable("PAYLOAD", new DataType(Identifier.of("CLOB"), null, null, null)))
                .primaryKey(new PrimaryKey(null, List.of(Identifier.of("ID"))))
                .addIndex(new Index(Identifier.of("IX_ORDER_CUSTOMER"),
                        List.of(new IndexColumn(Identifier.of("CUSTOMER_NAME"), SortDirection.ASC)),
                        IndexType.NORMAL, Description.empty()))
                .physicalOption("TABLESPACE", "app_data")
                .build();

        PostgreSqlDialect dialect = new PostgreSqlDialect();
        var script = new TableScriptGenerator(new TableDdlGenerator(new PostgreSqlColumnDefinitionGenerator()))
                .generate(table, dialect);
        var rendered = new PostgreSqlDdlRenderer().render(script,
                new RenderContext(dialect, new ScriptOptions(true, false, true, true, "\n"),
                        Clock.systemUTC(), Map.of()));

        assertEquals(5, rendered.statementCount());
        assertTrue(rendered.content().startsWith("\\set ON_ERROR_STOP on"));
        assertTrue(rendered.content().contains("CREATE TABLE sales.\"order\""));
        assertTrue(rendered.content().contains("id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"));
        assertTrue(rendered.content().contains("customer_name VARCHAR(200) NOT NULL"));
        assertTrue(rendered.content().contains("payload TEXT"));
        assertTrue(rendered.content().contains("TABLESPACE app_data"));
        assertTrue(rendered.content().contains("ADD CONSTRAINT pk_order"));
        assertTrue(rendered.content().contains("CREATE INDEX ix_order_customer\nON sales.\"order\" (customer_name ASC)"));
        assertTrue(rendered.content().contains("COMMENT ON TABLE sales.\"order\" IS 'Customer order'"));
    }
}
