package com.behsazan.schemaforge.generation.postgresql;

import com.behsazan.schemaforge.dialect.postgresql.PostgreSqlDialect;
import com.behsazan.schemaforge.domain.model.Column;
import com.behsazan.schemaforge.domain.valueobject.DataType;
import com.behsazan.schemaforge.domain.valueobject.DefaultValue;
import com.behsazan.schemaforge.domain.valueobject.Description;
import com.behsazan.schemaforge.domain.valueobject.Identifier;
import com.behsazan.schemaforge.generation.ddl.generator.table.postgresql.PostgreSqlColumnDefinitionGenerator;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class PostgreSqlColumnDefinitionGeneratorTest {

    private final PostgreSqlColumnDefinitionGenerator generator = new PostgreSqlColumnDefinitionGenerator();
    private final PostgreSqlDialect dialect = new PostgreSqlDialect();

    @Test
    void suppressesOracleSequenceDefaultForIdentityColumn() {
        Column column = new Column(
                Identifier.of("CITY_ID"),
                DataType.numeric("NUMBER", 4, null),
                false,
                new DefaultValue("BIM.SEQ_CITIES.NEXTVAL"),
                Description.empty(),
                true,
                1);

        String sql = generator.generate(column, dialect);

        assertEquals("city_id NUMERIC(4) GENERATED BY DEFAULT AS IDENTITY NOT NULL", sql);
        assertFalse(sql.contains("DEFAULT BIM.SEQ_CITIES.NEXTVAL"));
    }

    @Test
    void preservesDefaultForNonIdentityColumn() {
        Column column = new Column(
                Identifier.of("STATUS"),
                DataType.varchar("VARCHAR2", 20),
                false,
                new DefaultValue("'ACTIVE'"),
                Description.empty(),
                false,
                1);

        String sql = generator.generate(column, dialect);

        assertTrue(sql.contains("DEFAULT 'ACTIVE'"));
    }
}
