package com.behsazan.schemaforge.generation.oracle;

import static org.assertj.core.api.Assertions.assertThat;

import com.behsazan.schemaforge.domain.model.Column;
import com.behsazan.schemaforge.domain.enums.IndexType;
import com.behsazan.schemaforge.domain.enums.ReferentialAction;
import com.behsazan.schemaforge.domain.enums.SortDirection;
import com.behsazan.schemaforge.domain.model.CheckConstraint;
import com.behsazan.schemaforge.domain.model.DatabaseSchema;
import com.behsazan.schemaforge.domain.model.ForeignKey;
import com.behsazan.schemaforge.domain.model.Index;
import com.behsazan.schemaforge.domain.model.IndexColumn;
import com.behsazan.schemaforge.domain.model.PrimaryKey;
import com.behsazan.schemaforge.domain.model.Sequence;
import com.behsazan.schemaforge.domain.model.Table;
import com.behsazan.schemaforge.domain.model.UniqueKey;
import com.behsazan.schemaforge.domain.model.View;
import com.behsazan.schemaforge.domain.model.Synonym;
import com.behsazan.schemaforge.domain.valueobject.DataType;
import com.behsazan.schemaforge.domain.valueobject.DefaultValue;
import com.behsazan.schemaforge.domain.valueobject.Description;
import com.behsazan.schemaforge.domain.valueobject.Identifier;
import com.behsazan.schemaforge.domain.valueobject.QualifiedName;
import com.behsazan.schemaforge.generation.spi.DatabaseType;
import com.behsazan.schemaforge.generation.spi.GenerationContext;
import com.behsazan.schemaforge.generation.spi.GenerationOptions;
import java.nio.charset.StandardCharsets;
import java.time.Clock;
import java.util.Map;
import org.junit.jupiter.api.Test;

class OracleDdlGeneratorTest {
    @Test
    void generatesLegacySequenceDefaultStyleBeforeTable() {
        Sequence sequence = new Sequence(
                QualifiedName.of("LON", "SEQ_PROPOSEDS"),
                1,
                1,
                1L,
                9_999_999_999L,
                false,
                0,
                Description.empty());

        Table table = Table.builder("LON", "PROPOSEDS")
                .description("Proposed master")
                .addColumn(new Column(Identifier.of("PROPOSED_ID"), DataType.numeric("NUMBER", 10, null), false,
                        new DefaultValue("LON.SEQ_PROPOSEDS.NEXTVAL"), new Description("Identifier"), false, 1))
                .addColumn(new Column(Identifier.of("TITLE"), DataType.varchar("STRING", 200), true,
                        null, null, false, 2))
                .physicalOption("tablespace", "TS_LON")
                .build();

        DatabaseSchema schema = DatabaseSchema.builder("LON")
                .addSequence(sequence)
                .addTable(table)
                .build();
        GenerationContext context = new GenerationContext(schema, DatabaseType.ORACLE,
                new GenerationOptions(false, true, true, true, Map.of()), Clock.systemUTC());

        var result = new OracleDdlGenerator().generate(context);
        String sql = new String(result.artifacts().getFirst().content(), StandardCharsets.UTF_8);

        assertThat(result.hasErrors()).isFalse();
        assertThat(sql)
                .contains("CREATE SEQUENCE LON.SEQ_PROPOSEDS")
                .contains("INCREMENT BY 1")
                .contains("START WITH 1")
                .contains("MAXVALUE 9999999999")
                .contains("MINVALUE 1")
                .contains("NOCACHE")
                .contains("ORDER;")
                .contains("CREATE TABLE LON.PROPOSEDS")
                .contains("PROPOSED_ID NUMBER(10) DEFAULT LON.SEQ_PROPOSEDS.NEXTVAL NOT NULL")
                .doesNotContain("GENERATED BY DEFAULT AS IDENTITY")
                .contains("TABLESPACE TS_LON")
                .contains("COMMENT ON TABLE LON.PROPOSEDS IS 'Proposed master';")
                .contains("COMMENT ON COLUMN LON.PROPOSEDS.PROPOSED_ID IS 'Identifier';");

        assertThat(sql.indexOf("CREATE SEQUENCE")).isLessThan(sql.indexOf("CREATE TABLE"));
    }
    @Test
    void generatesConstraintsAndIndexesInDependencyOrder() {
        Table parent = Table.builder("LON", "PARENT")
                .addColumn(new Column(Identifier.of("ID"), DataType.numeric("NUMBER", 10, null), false,
                        null, null, false, 1))
                .primaryKey(new PrimaryKey(Identifier.of("PK_PARENT"), java.util.List.of(Identifier.of("ID"))))
                .build();

        Table child = Table.builder("LON", "CHILD")
                .addColumn(new Column(Identifier.of("ID"), DataType.numeric("NUMBER", 10, null), false,
                        null, null, false, 1))
                .addColumn(new Column(Identifier.of("PARENT_ID"), DataType.numeric("NUMBER", 10, null), false,
                        null, null, false, 2))
                .addColumn(new Column(Identifier.of("CODE"), DataType.varchar("STRING", 20), true,
                        null, null, false, 3))
                .primaryKey(new PrimaryKey(Identifier.of("PK_CHILD"), java.util.List.of(Identifier.of("ID"))))
                .addUniqueKey(new UniqueKey(Identifier.of("UK_CHILD_CODE"), java.util.List.of(Identifier.of("CODE"))))
                .addCheck(new CheckConstraint(Identifier.of("CK_CHILD_ID"), "ID > 0"))
                .addForeignKey(new ForeignKey(Identifier.of("FK_CHILD_PARENT"),
                        java.util.List.of(Identifier.of("PARENT_ID")), QualifiedName.of("LON", "PARENT"),
                        java.util.List.of(Identifier.of("ID")), ReferentialAction.CASCADE, ReferentialAction.NO_ACTION))
                .addIndex(new Index(Identifier.of("IX_CHILD_PARENT"),
                        java.util.List.of(new IndexColumn(Identifier.of("PARENT_ID"), SortDirection.DESC)),
                        IndexType.NORMAL, Description.empty()))
                .build();

        DatabaseSchema schema = DatabaseSchema.builder("LON").addTable(parent).addTable(child).build();
        GenerationContext context = new GenerationContext(schema, DatabaseType.ORACLE,
                new GenerationOptions(false, false, true, true, Map.of()), Clock.systemUTC());

        String sql = new String(new OracleDdlGenerator().generate(context).artifacts().getFirst().content(),
                StandardCharsets.UTF_8);

        assertThat(sql)
                .contains("ALTER TABLE LON.PARENT ADD CONSTRAINT PK_PARENT PRIMARY KEY (ID)\nUSING INDEX (CREATE UNIQUE INDEX LON.PK_PARENT ON LON.PARENT (ID) TABLESPACE ITS_LON);")
                .contains("ALTER TABLE LON.CHILD ADD CONSTRAINT UK_CHILD_CODE UNIQUE (CODE)\nUSING INDEX (CREATE UNIQUE INDEX LON.UK_CHILD_CODE ON LON.CHILD (CODE) TABLESPACE ITS_LON);")
                .contains("ALTER TABLE LON.CHILD ADD CONSTRAINT CK_CHILD_ID CHECK (ID > 0);")
                .contains("ALTER TABLE LON.CHILD ADD CONSTRAINT FK_CHILD_PARENT FOREIGN KEY (PARENT_ID) REFERENCES LON.PARENT (ID) ON DELETE CASCADE;")
                .contains("CREATE INDEX LON.IX_CHILD_PARENT ON LON.CHILD (PARENT_ID DESC)\nTABLESPACE ITS_LON;");

        assertThat(sql.indexOf("CREATE TABLE LON.CHILD"))
                .isLessThan(sql.indexOf("CONSTRAINT PK_CHILD"));
        assertThat(sql.indexOf("CONSTRAINT PK_CHILD"))
                .isLessThan(sql.indexOf("CONSTRAINT FK_CHILD_PARENT"));
        assertThat(sql.indexOf("CONSTRAINT FK_CHILD_PARENT"))
                .isLessThan(sql.indexOf("CREATE INDEX LON.IX_CHILD_PARENT"));
    }

    @Test
    void generatesViewsMaterializedViewsAndSynonymsInDependencyOrder() {
        Table table = Table.builder("CORE", "ACCOUNT")
                .addColumn(new Column(Identifier.of("ID"), DataType.numeric("NUMBER", 10, null), false,
                        null, null, false, 1))
                .build();

        View view = new View(
                QualifiedName.of("APP", "V_ACCOUNT"),
                "SELECT ID FROM CORE.ACCOUNT;",
                new Description("Account view"),
                false);
        View materializedView = new View(
                QualifiedName.of("APP", "MV_ACCOUNT"),
                "SELECT ID FROM CORE.ACCOUNT",
                new Description("Account materialized view"),
                true);
        Synonym privateSynonym = new Synonym(
                QualifiedName.of("APP", "ACCOUNT"),
                QualifiedName.of("CORE", "ACCOUNT"),
                false,
                Description.empty());
        Synonym publicSynonym = new Synonym(
                QualifiedName.of("APP", "ACCOUNT_PUBLIC"),
                QualifiedName.of("CORE", "ACCOUNT"),
                true,
                Description.empty());

        DatabaseSchema schema = DatabaseSchema.builder("APP")
                .addTable(table)
                .addView(view)
                .addView(materializedView)
                .addSynonym(privateSynonym)
                .addSynonym(publicSynonym)
                .build();
        GenerationContext context = new GenerationContext(schema, DatabaseType.ORACLE,
                new GenerationOptions(false, true, true, true, Map.of()), Clock.systemUTC());

        String sql = new String(new OracleDdlGenerator().generate(context).artifacts().getFirst().content(),
                StandardCharsets.UTF_8);

        assertThat(sql)
                .contains("CREATE OR REPLACE VIEW APP.V_ACCOUNT AS\nSELECT ID FROM CORE.ACCOUNT;")
                .contains("CREATE MATERIALIZED VIEW APP.MV_ACCOUNT\nAS\nSELECT ID FROM CORE.ACCOUNT;")
                .contains("CREATE OR REPLACE SYNONYM APP.ACCOUNT FOR CORE.ACCOUNT;")
                .contains("CREATE OR REPLACE PUBLIC SYNONYM ACCOUNT_PUBLIC FOR CORE.ACCOUNT;")
                .contains("COMMENT ON TABLE APP.V_ACCOUNT IS 'Account view';")
                .contains("COMMENT ON TABLE APP.MV_ACCOUNT IS 'Account materialized view';")
                .doesNotContain("CORE.ACCOUNT;;");

        assertThat(sql.indexOf("CREATE TABLE CORE.ACCOUNT"))
                .isLessThan(sql.indexOf("CREATE OR REPLACE VIEW APP.V_ACCOUNT"));
        assertThat(sql.indexOf("CREATE OR REPLACE VIEW APP.V_ACCOUNT"))
                .isLessThan(sql.indexOf("CREATE MATERIALIZED VIEW APP.MV_ACCOUNT"));
        assertThat(sql.indexOf("CREATE MATERIALIZED VIEW APP.MV_ACCOUNT"))
                .isLessThan(sql.indexOf("CREATE OR REPLACE SYNONYM APP.ACCOUNT"));
        assertThat(sql.indexOf("CREATE OR REPLACE SYNONYM APP.ACCOUNT"))
                .isLessThan(sql.indexOf("COMMENT ON TABLE APP.V_ACCOUNT"));
    }

}
