package com.behsazan.schemaforge.generation.oracle;

import static org.assertj.core.api.Assertions.assertThat;

import com.behsazan.schemaforge.domain.model.Column;
import com.behsazan.schemaforge.domain.model.DatabaseSchema;
import com.behsazan.schemaforge.domain.model.Sequence;
import com.behsazan.schemaforge.domain.model.Table;
import com.behsazan.schemaforge.domain.valueobject.DataType;
import com.behsazan.schemaforge.domain.valueobject.DefaultValue;
import com.behsazan.schemaforge.domain.valueobject.Description;
import com.behsazan.schemaforge.domain.valueobject.Identifier;
import com.behsazan.schemaforge.domain.valueobject.QualifiedName;
import com.behsazan.schemaforge.generation.spi.DatabaseType;
import com.behsazan.schemaforge.generation.spi.GenerationContext;
import com.behsazan.schemaforge.generation.spi.GenerationOptions;
import java.nio.charset.StandardCharsets;
import java.time.Clock;
import java.util.Map;
import org.junit.jupiter.api.Test;

class OracleDdlGeneratorTest {
    @Test
    void generatesLegacySequenceDefaultStyleBeforeTable() {
        Sequence sequence = new Sequence(
                QualifiedName.of("LON", "SEQ_PROPOSEDS"),
                1,
                1,
                1L,
                9_999_999_999L,
                false,
                0,
                Description.empty());

        Table table = Table.builder("LON", "PROPOSEDS")
                .description("Proposed master")
                .addColumn(new Column(Identifier.of("PROPOSED_ID"), DataType.numeric("NUMBER", 10, null), false,
                        new DefaultValue("LON.SEQ_PROPOSEDS.NEXTVAL"), new Description("Identifier"), false, 1))
                .addColumn(new Column(Identifier.of("TITLE"), DataType.varchar("STRING", 200), true,
                        null, null, false, 2))
                .physicalOption("tablespace", "TS_LON")
                .build();

        DatabaseSchema schema = DatabaseSchema.builder("LON")
                .addSequence(sequence)
                .addTable(table)
                .build();
        GenerationContext context = new GenerationContext(schema, DatabaseType.ORACLE,
                new GenerationOptions(false, true, true, true, Map.of()), Clock.systemUTC());

        var result = new OracleDdlGenerator().generate(context);
        String sql = new String(result.artifacts().getFirst().content(), StandardCharsets.UTF_8);

        assertThat(result.hasErrors()).isFalse();
        assertThat(sql).contains("CREATE SEQUENCE LON.SEQ_PROPOSEDS INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 NOCACHE ORDER;")
                .contains("CREATE TABLE LON.PROPOSEDS")
                .contains("PROPOSED_ID NUMBER(10) DEFAULT LON.SEQ_PROPOSEDS.NEXTVAL NOT NULL")
                .doesNotContain("GENERATED BY DEFAULT AS IDENTITY")
                .contains("TABLESPACE TS_LON")
                .contains("COMMENT ON TABLE LON.PROPOSEDS IS 'Proposed master';")
                .contains("COMMENT ON COLUMN LON.PROPOSEDS.PROPOSED_ID IS 'Identifier';");

        assertThat(sql.indexOf("CREATE SEQUENCE")).isLessThan(sql.indexOf("CREATE TABLE"));
    }
}
