package com.behsazan.schemaforge.comparison.column;

import com.behsazan.schemaforge.comparison.model.ComparisonDifference;
import com.behsazan.schemaforge.comparison.model.DifferenceSeverity;
import com.behsazan.schemaforge.comparison.model.DifferenceType;
import com.behsazan.schemaforge.domain.model.Column;

import java.util.Locale;
import java.util.Optional;

import org.springframework.stereotype.Component;


@Component
public final class IdentityComparisonRule extends AbstractColumnDifferenceRule {


    @Override
    public int order() {
        return 700;
    }


    @Override
    public Optional<ComparisonDifference> compare(
            Column documentColumn,
            Column databaseColumn) {


        if (isEquivalent(
                documentColumn,
                databaseColumn)) {

            return Optional.empty();
        }


        return Optional.of(
                changed(
                        documentColumn,
                        DifferenceType.IDENTITY_CHANGED,
                        DifferenceSeverity.HIGH,
                        "IDENTITY",
                        Boolean.toString(
                                documentColumn.identity()
                        ),
                        Boolean.toString(
                                databaseColumn.identity()
                        ),
                        "Column identity property differs"
                )
        );
    }



    private boolean isEquivalent(
            Column documentColumn,
            Column databaseColumn) {


        if (documentColumn.identity()
                == databaseColumn.identity()) {

            return true;
        }


        /*
         * DOCX:
         * GENERATED BY DEFAULT AS IDENTITY
         *
         * Oracle:
         * DEFAULT SCHEMA.SEQUENCE.NEXTVAL
         *
         * They represent the same generated value strategy.
         */
        return documentColumn.identity()
                && isSequenceDefault(databaseColumn);
    }



    private boolean isSequenceDefault(
            Column column) {


        if (column.defaultValue() == null
                || !column.defaultValue().isPresent()) {

            return false;
        }


        String expression =
                column.defaultValue()
                        .expression();


        return expression != null
                && expression
                .toUpperCase(Locale.ROOT)
                .contains("NEXTVAL");
    }
}