package com.behsazan.schemaforge.generation.ddl.generator.table;

import com.behsazan.schemaforge.dialect.oracle.OracleDialect;
import com.behsazan.schemaforge.domain.model.Column;
import com.behsazan.schemaforge.domain.model.Table;
import com.behsazan.schemaforge.domain.valueobject.DataType;
import com.behsazan.schemaforge.domain.valueobject.DefaultValue;
import com.behsazan.schemaforge.domain.valueobject.Description;
import com.behsazan.schemaforge.domain.valueobject.Identifier;
import com.behsazan.schemaforge.generation.ddl.generator.table.oracle.OracleColumnDefinitionGenerator;
import com.behsazan.schemaforge.generation.ddl.model.DdlPhase;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class TableDdlGeneratorTest {

    @Test
    void generatesOracleCreateTableStatement() {
        Table table = Table.builder("BANK", "CUSTOMER")
                .addColumn(new Column(Identifier.of("ID"), DataType.numeric("NUMBER", 19, 0), false,
                        null, null, true, 1))
                .addColumn(new Column(Identifier.of("NAME"), DataType.varchar("VARCHAR2", 200), false,
                        null, null, false, 2))
                .addColumn(new Column(Identifier.of("STATUS"), DataType.varchar("VARCHAR2", 20), false,
                        new DefaultValue("'ACTIVE'"), Description.empty(), false, 3))
                .build();

        var statement = new TableDdlGenerator(new OracleColumnDefinitionGenerator())
                .generate(table, new OracleDialect(), 10);

        assertEquals(DdlPhase.TABLES, statement.order().phase());
        assertEquals(10, statement.order().position());
        String sql = statement.fragments().getFirst().value();
        assertTrue(sql.contains("CREATE TABLE BANK.CUSTOMER"));
        assertTrue(sql.contains("ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL"));
        assertTrue(sql.contains("STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL"));
    }
    @Test
    void generatesOracleVirtualColumnWithoutCreatingAnotherGeneratorClass() {
        Table table = Table.builder("BANK", "ACCOUNT_BALANCE")
                .addColumn(new Column(Identifier.of("DEBIT_AMOUNT"), DataType.numeric("NUMBER", 18, 2), false,
                        null, null, false, 1))
                .addColumn(new Column(Identifier.of("CREDIT_AMOUNT"), DataType.numeric("NUMBER", 18, 2), false,
                        null, null, false, 2))
                .addColumn(new Column(Identifier.of("NET_AMOUNT"), DataType.numeric("NUMBER", 18, 2), true,
                        null, null, false, 3, "CREDIT_AMOUNT - DEBIT_AMOUNT"))
                .build();

        var statement = new TableDdlGenerator(new OracleColumnDefinitionGenerator())
                .generate(table, new OracleDialect(), 10);

        String sql = statement.fragments().getFirst().value();
        assertTrue(sql.contains(
                "NET_AMOUNT NUMBER(18,2) GENERATED ALWAYS AS (CREDIT_AMOUNT - DEBIT_AMOUNT) VIRTUAL"));
    }

}
