package com.behsazan.schemaforge.specification.adapter.docx;

import com.behsazan.schemaforge.dialect.postgresql.PostgreSqlDialect;
import com.behsazan.schemaforge.generation.ddl.generator.script.TableScriptGenerator;
import com.behsazan.schemaforge.generation.ddl.generator.table.TableDdlGenerator;
import com.behsazan.schemaforge.generation.ddl.generator.table.postgresql.PostgreSqlColumnDefinitionGenerator;
import com.behsazan.schemaforge.generation.ddl.model.RenderContext;
import com.behsazan.schemaforge.generation.ddl.model.ScriptOptions;
import com.behsazan.schemaforge.generation.ddl.renderer.postgresql.PostgreSqlDdlRenderer;
import com.behsazan.schemaforge.specification.spi.SpecificationSource;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Clock;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * End-to-end regression test for the real CITIES DOCX fixture.
 *
 * <p>The test covers the complete PostgreSQL path:</p>
 *
 * <pre>
 * DOCX -> canonical schema -> PostgreSQL table script -> rendered SQL file
 * </pre>
 */
class PostgreSqlCitiesDocxEndToEndTest {

    @TempDir
    Path temporaryDirectory;

    @Test
    void generatesCitiesSqlWithoutOracleSequenceDefaultOnIdentityColumn() throws Exception {
        var parser = new DocxSpecificationParser();

        try (InputStream input = getClass().getResourceAsStream(
                "/samples/docx/BIM.TBL.CITIES.V1.1.docx")) {
            assertThat(input)
                    .as("CITIES DOCX regression fixture")
                    .isNotNull();

            var schema = parser.parse(new SpecificationSource(
                    "BIM.TBL.CITIES.V1.1.docx",
                    input));

            var cities = schema.tables().getFirst();
            var cityId = cities.findColumn("CITY_ID").orElseThrow();

            assertThat(cityId.identity())
                    .as("CITY_ID must be recognized as an identity column")
                    .isTrue();
            assertThat(cityId.defaultValue().expression())
                    .isEqualTo("BIM.SEQ_CITIES.NEXTVAL");

            PostgreSqlDialect dialect = new PostgreSqlDialect();
            TableScriptGenerator generator = new TableScriptGenerator(
                    new TableDdlGenerator(new PostgreSqlColumnDefinitionGenerator()));
            PostgreSqlDdlRenderer renderer = new PostgreSqlDdlRenderer();
            RenderContext context = new RenderContext(
                    dialect,
                    new ScriptOptions(
                            true,
                            false,
                            true,
                            true,
                            System.lineSeparator()),
                    Clock.systemUTC(),
                    Map.of());

            String sql = renderer.render(
                    generator.generate(cities, dialect),
                    context).content();

            Path output = temporaryDirectory.resolve("BIM.CITIES.sql");
            Files.writeString(output, sql, StandardCharsets.UTF_8);
            String generatedFile = Files.readString(output, StandardCharsets.UTF_8);

            assertThat(output).isRegularFile();
            assertThat(generatedFile)
                    .contains("city_id NUMERIC(4) GENERATED BY DEFAULT AS IDENTITY NOT NULL")
                    .doesNotContain("GENERATED BY DEFAULT AS IDENTITY DEFAULT")
                    .doesNotContain("DEFAULT BIM.SEQ_CITIES.NEXTVAL");
        }
    }
}
