package com.behsazan.schemaforge.generation.oracle;

import com.behsazan.schemaforge.domain.model.Column;
import com.behsazan.schemaforge.domain.model.DatabaseSchema;
import com.behsazan.schemaforge.domain.model.Table;
import com.behsazan.schemaforge.generation.model.SqlDocument;
import com.behsazan.schemaforge.generation.model.SqlSection;
import com.behsazan.schemaforge.generation.model.SqlStatement;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

public final class OracleTableGenerator {
    private final OracleCanonicalTypeMapper typeMapper;

    public OracleTableGenerator() {
        this(new OracleCanonicalTypeMapper());
    }

    public OracleTableGenerator(OracleCanonicalTypeMapper typeMapper) {
        this.typeMapper = typeMapper;
    }

    public SqlDocument generate(DatabaseSchema schema, boolean includeComments) {
        List<SqlStatement> tables = new ArrayList<>();
        List<SqlStatement> comments = new ArrayList<>();
        int order = 0;
        for (Table table : schema.tables().stream().sorted(Comparator.comparing(t -> t.qualifiedName().toString())).toList()) {
            tables.add(new SqlStatement(buildTable(table), "TABLE", table.qualifiedName().toString(), order++));
            if (includeComments) addComments(table, comments);
        }
        List<SqlSection> sections = new ArrayList<>();
        sections.add(new SqlSection("Tables", 100, tables));
        if (!comments.isEmpty()) sections.add(new SqlSection("Comments", 200, comments));
        return new SqlDocument(sections);
    }

    private String buildTable(Table table) {
        StringBuilder sql = new StringBuilder("CREATE TABLE ")
                .append(table.qualifiedName()).append("\n(\n");
        List<Column> columns = table.columns().stream()
                .sorted(Comparator.comparing(c -> c.ordinalPosition() == null ? Integer.MAX_VALUE : c.ordinalPosition()))
                .toList();
        for (int i = 0; i < columns.size(); i++) {
            sql.append("    ").append(buildColumn(columns.get(i)));
            if (i < columns.size() - 1) sql.append(',');
            sql.append('\n');
        }
        sql.append(")");
        String tablespace = table.physicalOptions().get("tablespace");
        if (tablespace != null && !tablespace.isBlank()) sql.append(" TABLESPACE ").append(tablespace.trim());
        sql.append(';');
        return sql.toString();
    }

    private String buildColumn(Column column) {
        StringBuilder sql = new StringBuilder(column.name().value()).append(' ').append(typeMapper.map(column.dataType()));
        if (column.defaultValue().isPresent()) sql.append(" DEFAULT ").append(column.defaultValue().expression());
        if (column.identity()) sql.append(" GENERATED BY DEFAULT AS IDENTITY");
        if (!column.nullable()) sql.append(" NOT NULL");
        return sql.toString();
    }

    private void addComments(Table table, List<SqlStatement> comments) {
        if (!table.description().isEmpty()) {
            comments.add(new SqlStatement("COMMENT ON TABLE " + table.qualifiedName() + " IS '" + escape(table.description().value()) + "';",
                    "TABLE_COMMENT", table.qualifiedName().toString(), comments.size()));
        }
        for (Column column : table.columns()) {
            if (!column.description().isEmpty()) {
                comments.add(new SqlStatement("COMMENT ON COLUMN " + table.qualifiedName() + "." + column.name() + " IS '" + escape(column.description().value()) + "';",
                        "COLUMN_COMMENT", table.qualifiedName() + "." + column.name(), comments.size()));
            }
        }
    }

    private String escape(String value) {
        return value.replace("'", "''");
    }
}
