package com.behsazan.schemaforge.validation.domain;

public enum ValidationCode {
    REQUIRED_VALUE,
    DUPLICATE_TABLE,
    DUPLICATE_COLUMN,
    DUPLICATE_CONSTRAINT,
    DUPLICATE_INDEX,
    DUPLICATE_SEQUENCE,
    INVALID_IDENTIFIER,
    IDENTIFIER_TOO_LONG,
    RESERVED_WORD,
    INVALID_REFERENCE,
    MISSING_REFERENCED_TABLE,
    MISSING_REFERENCED_COLUMN,
    COLUMN_COUNT_MISMATCH,
    UNSUPPORTED_DATA_TYPE,
    INVALID_DATA_TYPE_PARAMETERS,
    INVALID_PRIMARY_KEY,
    INVALID_UNIQUE_KEY,
    INVALID_FOREIGN_KEY,
    INVALID_INDEX,
    INVALID_SEQUENCE,
    MISSING_PRIMARY_KEY,
    NULLABLE_PRIMARY_KEY_COLUMN,
    SPELLING_WARNING
}
