package com.behsazan.schemaforge.generation.ddl.generator.table.postgresql;

import com.behsazan.schemaforge.dialect.DatabaseCapability;
import com.behsazan.schemaforge.dialect.DatabaseDialect;
import com.behsazan.schemaforge.dialect.DatabaseProduct;
import com.behsazan.schemaforge.domain.model.Column;
import com.behsazan.schemaforge.generation.ddl.generator.table.*;
import java.util.Objects;

public final class PostgreSqlColumnDefinitionGenerator implements ColumnDefinitionGenerator {
    @Override
    public DatabaseProduct product() {
        return DatabaseProduct.POSTGRESQL;
    }

    private final IdentifierSqlRenderer identifiers = new IdentifierSqlRenderer();
    private final DataTypeSqlRenderer dataTypes = new DataTypeSqlRenderer();
    @Override public String generate(Column column, DatabaseDialect dialect) {
        Objects.requireNonNull(column); Objects.requireNonNull(dialect);
        StringBuilder sql = new StringBuilder(identifiers.render(column.name(), dialect))
                .append(' ').append(dataTypes.render(column.dataType(), dialect));
        if (column.identity()) {
            if (!dialect.supports(DatabaseCapability.IDENTITY)) {
                throw new TableGenerationException("Identity columns are not supported by " + dialect.name());
            }
            sql.append(" GENERATED BY DEFAULT AS IDENTITY");
        }
        // PostgreSQL does not allow an identity column to also declare a DEFAULT expression.
        // Oracle-style sequence defaults (for example BIM.SEQ_CITIES.NEXTVAL) may still be
        // present in the canonical model because the DOCX parser is database-independent.
        // Identity semantics take precedence for PostgreSQL, so the default is intentionally
        // suppressed only for identity columns.
        if (!column.identity() && column.defaultValue().isPresent()) {
            sql.append(" DEFAULT ").append(column.defaultValue().expression());
        }
        if (!column.nullable()) sql.append(" NOT NULL");
        return sql.toString();
    }
}
